### ISSUE TITLE
More/Tips: Empty tooltip

### ISSUE THREAD

**Issue by muffinmad** [mootools/mootools-more#1298]
Don't show tooltip if there are nothing to show
http://jsfiddle.net/6v48emj6/

**Comment by SergioCrisostomo** [comment]
@muffinmad could you explain your issue better? do you mean you wanted the tooltip to not show if its empty?

**Comment by muffinmad** [comment]
@SergioCrisostomo Yes, exactly. Also tooltip must be hidden while moving mouse from element with tooltip to element without tooltip.

**Comment by muffinmad** [comment]
@SergioCrisostomo Is it adding a spec required to make pull request?

**Comment by timwienk** [comment]
As a configurable option, I think this would be a good idea to add.

**Comment by muffinmad** [comment]
@timwienk Done. https://github.com/mootools/mootools-more/pull/1299

**Comment by timwienk** [comment]
Oh, I didn't notice the Pull Request. Quickly scanning it looks good, would be nice if you can adapt it slightly to match the [syntax and coding style conventions](https://github.com/mootools/mootools-core/wiki/Syntax-and-Coding-Style-Conventions), that mostly comes down to:
* whitespace between `){`,
* we generally camelCase variable names, rather than under_scoring them (not sure if that's in the conventions actually),
* instead of `show_tip = show_tip || Boolean(content);` I think you can just add `showTip = true;` in the body of the `if (content)` statement that's above it already.)

And I'll make sure to alert other devs, so they can have an opinion on it as well.

**Comment by muffinmad** [comment]
And done.

**Comment by anutron** [comment]
Well done. Ship it!
