### ISSUE TITLE
Request Periodical

### ISSUE THREAD

**Issue by Miscellaneous** [mootools/mootools-more#1309]
Request Periodical data passed with StartTimer is frozen ( id:0, will never change)

		var i = 0;
		var myRequest = new Request.JSON({
			url: 'update.php',
			method: 'POST',
			initialDelay: 1000,
			delay: 5000,
			onComplete: function( json )
			{
				i++;
			}
		});
		myRequest.startTimer({ id: i });

**Comment by SergioCrisostomo** [comment]
Request is not frozen, what is frozen is the value of `i`. 
When you run the method `.startTimer({ id: i }); ` the value of `i` will be the value it had at the moment and not keep the pointer to the variable.

You could use another approach, which is getting the new value of `i` at the moment the `.send()` is called. Something like this: http://jsfiddle.net/4mwsyosv/

**Comment by timwienk** [comment]
The problem seems to be that you assume the `i` variable is passed by reference. However, primitives (like numbers and strings) are passed by value. Therefore, changing `i` later has no effect on the value of the `id`-property of the object you create on the last line.

Sergio's solution works to work around that. Another option, closer to your own implementation, is to use the fact that objects **are** passed by reference. So instead of `i` being a primitive, make it an object. Like:

```javascript
var i = {id: 0};
var myRequest = new Request.JSON({
    url: 'update.php',
    method: 'POST',
    initialDelay: 1000,
    delay: 5000,
    onComplete: function(){
        i.id++;
    }
});
myRequest.startTimer(i);
```

**Comment by SergioCrisostomo** [comment]
I close this now since its not a MooTools problem and you got input on how to solve the problem. Leav a comment if you still have problems.

Cheers

**Comment by Miscellaneous** [comment]
Perfect, solution made sense. Maybe your example belong to the MooTools Documents.

Regards

Dan
