### ISSUE TITLE
Docs: missing part?

### ISSUE THREAD

**Issue by Manaus** [mootools/mootools-more#1312]
Hello, 
I think there's a missing part regarding Form.Validator Constructor. Clicking on the link in the left column does not work, and in the text there seems to be a odd gap. Here is a [grab](https://www.evernote.com/l/AF-_EAtRYp1AtqQrKFdWgs5jJJX6ekFyPTM) of the screen.

Thanks!

**Comment by SergioCrisostomo** [comment]
Thank you for pointing this out.

The content looks good in the Github file:
https://github.com/mootools/mootools-more/blob/master/Docs/Forms/Form.Validator.md
but is parsing wrong in the website.
If you have time to check what is making that `.md` file being wrong parsed
in the website would be great.
Otherwise I can take a look at it soon.

**Comment by Manaus** [comment]
Thanks Sergio!
I'm checking the file shortly...

**Comment by Manaus** [comment]
After a speed check I found these issues: 

- **Locale: Form Validator** is not present in the submenu on the left
- The case might be also the same regarding the list **Keys/Values**
- Lines 37 and 38 of the md git version are inverted on the website
- From there to line 69 there is the gap regarding the Constructor
- In the left column, Form.Validator is present twice, first below Form.Validator.Inline, second time below Date
- The list item *Note that the property must be decodable by JSON.decode [...]* and the following are not contained within a `ul` tag

**Comment by Manaus** [comment]
Not sure about this one: at the section **Form.Validator Method: Constructor** > **Events** of the file 
https://github.com/mootools/mootools-more/blob/master/Docs/Forms/Form.Validator.md
the events are without `on`: *formValidate*, *elementFail* while in the analogous section in **Form.Validator.Inline** the events keep the `on` part: *onShowAdvice* etc.

**Comment by SergioCrisostomo** [comment]
The .md files are being compiled directly into the website (
https://github.com/mootools/website/blob/master/lib/compile-md.js). The
problem is either Markdown formatting problems in the .md file that bug the
compiler, or some problems with the parser.

If you want to test this you need to install the website locally and test.
I will do that later this week otherwise (currently traveling).

**Comment by Manaus** [comment]
Thanks Sergio, I tried to build the website locally but the install procedure of node modules raises a lot of errors I'm not proficient enough to understand, sorry I can't help in the short time. 
In the meanwhile I tried to compile the .md flles with Codekit, Marked, Mou and they look fine...

**Comment by SergioCrisostomo** [comment]
@Manaus so now I was able to look properly at this and it is a bug. 
I opened a new issue in the website repo (https://github.com/mootools/website/issues/209) and will fix it there.

Thank you for reporting this!

**Comment by Manaus** [comment]
Great Sergio! Glad to help in some way
I suppose this specific issue may be closed? Not so much proficient in github ways

**Comment by SergioCrisostomo** [comment]
I will leave it open until I fix this, in case more people report same problem.

Cheers

**Comment by SergioCrisostomo** [comment]
This has been fixed, and is online since a while ago. I just forgot to close it.

@Manaus thank you for reporting this!

**Comment by Manaus** [comment]
Eeeh! Great! Thanks!
