### ISSUE TITLE
IPv6 URI parse error

### ISSUE THREAD

**Issue by ngosang** [mootools/mootools-more#1318]
Hello, I'm one of the qBittorrent developers. You can read the full discussion here https://github.com/qbittorrent/qBittorrent/issues/3621

The problem appears when the base URL contains an IPv6 address, i.e. `http://[::1]:8080/` and we do:
```js
var url = new URI('sync/maindata');
```
The expected result is:
```
url = http://[::1]:8080/sync/maindata
```
but we get this instead:
```
url = http://[/:1%5D:8080/:1%5D:8080/sync/maindata
```
I think there is a problem in this regex https://github.com/mootools/mootools-more/blob/48fdc088d58acb96c001e1781236ac1602d0f386/Source/Types/URI.js#L42

**Comment by ngosang** [comment]
Is anyone working on this?

**Comment by SergioCrisostomo** [comment]
@ngosang not yet. If you have time to send a fix would be great. Otherwise we will catch up with this some time soon.

**Comment by ngosang** [comment]
That regular expression scares me. We want to include a fix for that in the next release if it's ready on time. Thanks.

**Comment by boppy** [comment]
As there is no validation for IPv4 or Host Names the needed extension to the regex is simple:

```javascript
var regex = /^(?:(\w+):)?(?:\/\/(?:(?:([^:@\/]*):?([^:@\/]*))?@)?(\[[A-Fa-f0-9:]+\]|[^:\/?#]*)(?::(\d*))?)?(\.\.?$|(?:[^?#\/]*\/)*)([^?#]*)(?:\?([^#]*))?(?:#(.*))?/;
```
It simply as:
```
Old Host-Part:                   ([^:\/?#]*)
New Host-Part: (\[[A-Fa-f0-9:]+\]|[^:\/?#]*)
```

Just added the detection of "[" and "]" and a (very, very basic) validation. It allowes upper and lower A-F, Numbers and colons.

So it will also allow [:::::] or [1] - both not valid, but as the old RegEx has no validation I tried to keep my RegEx as short/simple as possible.

Check at:
http://jsfiddle.net/pLyhehor/3/

PS: This is only to check the regex. The URI6-Class doesn't work if the host is not passed with the argument due to missing URI.base-re-assignment (Line 159 and/or 48/52 in the mentioned file).

**Comment by SergioCrisostomo** [comment]
@boppy do you have time to send a PR with some specs for that? 

That would be :ice_cream:

**Comment by SergioCrisostomo** [comment]
Fixed by https://github.com/mootools/mootools-more/issues/1322
